WEBSOCKET ws://localhost:8080/chat/test/VU1

###
WEBSOCKET ws://localhost:8080/chat/1
Authorization: Bearer eyJhbGciOiJIzI1NiJ9.eyJpZCI6InRlc3RzYmwiLCJuaWNrbmFtZSI6InRlc3RzYmwiLCJleHAiOjE3MDM1OTI0NzgsImlhdCI6MTcwMzU5MTU3OH0.l_ehF3EAF4KZ9DOJVXg6WWM7-haMbLVbrl4HTSwshCc